openapi: 3.0.0
info:
  description: |
    Covid-Fighter API
  version: "1.0.0"
  title: Covid Fighter
servers:
  - description: Covid Fighter Website
    url: http://covid19fighter.me
tags:
  - name: Restaurant
    description: A restaurant 
  - name: Hospital
    description: A hospital
  - name: GroceryStore
    description:  A grocery store
paths:

  /Restaurants/{id}/:
    get:
      tags:
        - Restaurant
      summary: restaurants by id
      operationId: getRestaurantByID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          description: ID of the Restaurant
          required: true
      responses:
        '200':
          description: 'Sample response: Details about a Restaurant by ID'
          headers:
            restaurant-obj:
              description: Restaurant Object with Specific ID Given
              schema:
                type: object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restaurant'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /Restaurants/:
    get:
      tags:
        - Restaurant
      summary: restaurants by query
      description: Get restaurants that fit a specific query
      operationId: getRestaurantsByQuery
      parameters:
        - in: query
          name: city
          schema:
            type: string
          description: City in which Restaurant is located
          required: false
        - in: query  
          name: open_status
          schema:
            type: integer
          description: Open Status of Restaurant
          required: false
        - in: query
          name: type
          schema:
            type: string
          description: Type of Restaurant
          required: false
      responses:
        '200':
          description: 'Sample response: Details about a Restaurant by Query'
          headers:
            restaurant-array:
              description: Restaurant Array with Specific Query Given
              schema:
                type: array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestaurantArray'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /Hospitals/{id}/:
    get:
      tags:
        - Hospital
      summary: hospitals by id
      operationId: getHospitalByID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          description: ID of the Hospital
          required: true
      responses:
        '200':
          description: 'Sample response: Details about a Hospital by ID'
          headers:
            hospital-obj:
              description: Hospital Object with Specific ID Given
              schema:
                type: object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hospital'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /Hospitals/:
    get:
      tags:
        - Hospital
      summary: hospitals by query
      description: Get hospitals that fit a specific query
      operationId: getHospitalsByQuery
      parameters:
        - in: query
          name: city
          schema:
            type: string
          description: City in which Hospital is located
          required: false
        - in: query
          name: open_status
          schema:
            type: integer
          description: Open Status of Hospital
          required: false
      responses:
        '200':
          description: 'Sample response: Details about a Hospital by Query'
          headers:
            hospital-array:
              description: Hospital Array with Specific Query Given
              schema:
                type: array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HospitalArray'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /GroceryStores/{id}/:
    get:
      tags:
        - GroceryStore
      summary: grocery stores by id
      operationId: getGroceryStoreByID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          description: ID of the GroceryStore
          required: true
      responses:
        '200':
          description: 'Sample response: Details about a GroceryStore by ID'
          headers:
            grocerystore-obj:
              description: GroceryStore Object with Specific ID Given
              schema:
                type: object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroceryStore'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /GroceryStores/:
    get:
      tags:
        - GroceryStore
      summary: grocery stores by query
      description: Get grocery stores that fit a specific query
      operationId: getGroceryStoresByQuery
      parameters:
        - in: query
          name: city
          schema:
            type: string
          description: City in which GroceryStore is located
          required: false
        - in: query
          name: open_status
          schema:
            type: integer
          description: Open Status of GroceryStore
          required: false
      responses:
        '200':
          description: 'Sample response: Details about a GroceryStore by Query'
          headers:
            grocerystore-array:
              description: GroceryStore Array with Specific Query Given
              schema:
                type: array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroceryStoreArray'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



components:
  schemas:
    Restaurant:
      type: object
      required:
        - id
        - name
        - city
        - open_status
        - type
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        city:
          type: string
        open_status:
          type: integer
          format: int32
        type: 
          type: string
    RestaurantArray:
      type: array
      items:
        $ref: '#/components/schemas/Restaurant'
    Hospital:
      type: object
      required:
        - id
        - name
        - city
        - open_status
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        city:
          type: string
        open_status:
          type: integer
          format: int32
    HospitalArray:
      type: array
      items:
        $ref: '#/components/schemas/Hospital'
    GroceryStore:
      type: object
      required:
        - id
        - name
        - city
        - open_status
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        city:
          type: string
        open_status:
          type: integer
          format: int32
    GroceryStoreArray:
      type: array
      items:
        $ref: '#/components/schemas/GroceryStore'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string