openapi: 3.0.0
info:
  description: |
    Covid-Fighter API
  version: "1.0.0"
  title: Covid Fighter
servers:
  - description: Covid Fighter Website
    url: http://covid19fighter.me
tags:
  - name: Restaurant
    description: A restaurant 
  - name: Hospital
    description: A hospital
  - name: GroceryStore
    description:  A grocery store
paths:
  /Hospital/nearby/{drugstore_id}:
    get:
      tags:
        - Hospital
      summary: hospitals nearby drugstore
      description: Get hospitals within the same zipcode as a given drugstore
      operationId: getHospitalsNearbyDrugstore
      parameters:
        - in: path
          name: drugstore_id
          schema:
            type: string
          description: ID of drugstore to check nearby hospitals with.
          required: true
      responses:
        '200':
          description: 'Sample response: Details about hospitals near to drugstore'
          headers:
            hospital-objs:
              description: Hospital Objects nearby specific Drugstore
              schema:
                type: array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HospitalArray'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /Hospital/:
    get:
      tags:
        - Hospital
      summary: hospitals by query
      description: Get hospitals that fit a specific query
      operationId: getHospitalsByQuery
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: Name of Hospital
        - in: query
          name: city
          schema:
            type: string
          description: City in which Hospital is located
        - in: query
          name: rating
          schema:
            type: string
          description: Rating of Hospital
      responses:
        '200':
          description: 'Sample response: Details about a Hospital by Query'
          headers:
            hospital-array:
              description: Hospital Array with Specific Query Given
              schema:
                type: array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HospitalArray'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /Drugstore/nearby/{hospital_id}:
    get:
      tags:
        - Drugstore
      summary: drugstores nearby hospital
      description: Get drugstores within the same zipcode as a given hospital
      operationId: getDrugstoresNearbyHospital
      parameters:
        - in: path
          name: hospital_id
          schema:
            type: string
          description: ID of hospital to check nearby drugstores with.
          required: true
      responses:
        '200':
          description: 'Sample response: Details about drugstores near to hospital'
          headers:
            drugstore-objs:
              description: Drugstores Object nearby specific Hospital
              schema:
                type: array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DrugstoreArray'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /Drugstore/:
    get:
      tags:
        - Drugstore
      summary: drugstores by query
      description: Get drugstores that fit a specific query
      operationId: getDrugstoresByQuery
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: Name of Drugstore
        - in: query
          name: city
          schema:
            type: string
          description: City in which Drugstore is located
        - in: query
          name: rating
          schema:
            type: number
            format: double
          description: Rating of Drugstore
      responses:
        '200':
          description: 'Sample response: Details about a Drugstore by Query'
          headers:
            drugstore-array:
              description: Drugstore Array with Specific Query Given
              schema:
                type: array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DrugstoreArray'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /City/{city_id}/:
    get:
      tags:
        - City
      summary: city by id
      description: Get city that corresponds with the specific id
      operationId: getCityByID
      parameters:
        - in: path
          name: city_id
          schema:
            type: integer
          description: ID of the City
          required: true
      responses:
        '200':
          description: 'Sample response: Details about a City by ID'
          headers:
            restaurant-obj:
              description: City Object with Specific ID Given
              schema:
                type: object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /City/:
    get:
      tags:
        - City
      summary: cities by query
      description: Get cities that fit a specific query
      operationId: getCitiesByQuery
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: Name of City
          required: false
      responses:
        '200':
          description: 'Sample response: Details about a City by Query'
          headers:
            restaurant-array:
              description: City Array with Specific Query Given
              schema:
                type: array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CityArray'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



components:
  schemas:
    Drugstore:
      type: object
      description: A hospital
      required:
        - id
        - name
        - address
        - zipcode
        - city
        - hospitals_nearby
      properties:
        id:
          type: string
        name:
          type: string
        address:
          type: string
        zipcode:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        opening_hours:
          type: string
        business_status:
          type: string
        rating:
          type: number
          format: double
        website:
          type: string
        google_maps_url:
          type: string
        phone_number:
          type: string
        city:
          type: integer
        hospitals_nearby:
          type: array
          items:
            type: integer
    DrugstoreArray:
      type: array
      items:
        $ref: '#/components/schemas/Drugstore'
    Hospital:
      type: object
      description: A hospital
      required:
        - id
        - name
        - address
        - zipcode
        - city
        - drugstores_nearby
      properties:
        id:
          type: string
        name:
          type: string
        address:
          type: string
        zipcode:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        opening_hours:
          type: string
        business_status:
          type: string
        rating:
          type: number
          format: double
        website:
          type: string
        google_maps_url:
          type: string
        phone_number:
          type: string
        city:
          type: integer
        drugstores_nearby:
          type: array
          items:
            type: integer
    HospitalArray:
      type: array
      items:
        $ref: '#/components/schemas/Hospital'
    City:
      type: object
      description: A city
      required:
        - id
        - name
        - state
        - zipcode
        - latitude
        - longitude
        - population
        - hospitals
        - drugstores
      properties:
        id:
          type: integer
        name:
          type: string
        state:
          type: string
        zipcode:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        population:
          type: integer
        hospitals:
          type: array
          items:
            type: string
        drugstores:
          type: array
          items:
            type: string
    CityArray:
      type: array
      items:
        $ref: '#/components/schemas/City'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string